
server:
  port: 8082 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product    
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order        
  
  security:
    oauth2:
      client:
        keycloak:
          client-id: spring-cloud-gateway-client 
          client-secret: 9b1302b7-4198-497d-9e58-41d809b21722  
          authorization-grant-type: authorization_code
          redirectUriTemplate: http://localhost:8082/login/oauth2/code/spring-cloud-gateway-client
        provider:
          keycloak:
            authorization-uri:http://localhost:8080/auth/realms/microservices-project-realm 