
server:
  port: 8080 

management:
  endpoint:
    gateway:
      enable: true
  endpoints:
    web:
      exposure:
        include: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

ribbon:
  eureka:
    enabled: false
        
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: http://W4RR100R:product-service
          predicates:
            - Path=/api/product/**    
       
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
            
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
       
         
                
  
  
