
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.2:3306/inventoryservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
  
 jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
         ddl-auto: update

 sleuth:
    integration:
          enabled: true          
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
      
management:
  endpoints:
    web:
      exposure:
         include: "*"
         
