server:
  port: 8003
  error:
    include-message: always
    include-binding-errors: always
spring:
  zipkin: 
   base-url: http://localhost:9411
             
  sleuth:
    sampler:
     probability: 1.0      
 kafka:
    bootstrap.servers: localhost:9092
    template:
        default: notificationTopic
    consumer:
        group-id: notificationId
        key-deserializer: org.apache.kafka.comon.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer    
        properties.spring.json.type.mapping: event:com.example.notificationservice.OrderPlacedEvent     

eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  
      
