server:
  port: 8087
  error:
    include-message: always
    include-binding-errors: always
spring:
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0: 
           destination: notification-events    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
      
