server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
    include-binding-errors: always
spring:
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0: 
           destination: notification-events    
  seuth:
    circuitbreaker:
          enabled: false
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
