server:
  port: 8087
  error:
    include-message: always
    include-binding-errors: always
spring:
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0: 
           destination: notification-events    

eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
