server:
  port: 8087
  error:
    include-message: always
    include-binding-errors: always
spring:
  rabbitmq: 
      host: localhost
      port: 5672
      user: guest
      password: guest   
  cloud:
    stream:
      bindings:
        notificationEventSupplier-out-0: 
           destination: notification-events    
  sleuth:
      enabled: true
      sampler:
         percentage: 1
  zipkin:
      enabled: true
      baseUrl: http://${tracking-host:tracking}:9411                  
                    
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
      
