server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/orderservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: myPasswd123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
         ddl-auto: update
  cloud:
    stream:
      bindings:
         notificationEventSupplier-out-0: 
           destination: notification-events
           binder: kafka
  
       
  sleuth:
    circuitbreaker:
          enabled: false
    integration:
          enabled: true   
  
  
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
         include: "*"      
      
zipkin: http://localhost:9411
