server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/orderservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mypass123
  rabbitmq: 
      host: localhost
      port: 5672
      user: guest
      password: guest   
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
         ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
