
server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb: 
        uri: mongodb://admin:admin@localhost:27017/product-service?authSource=admin

eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
         include: "*"      
