
server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb: 
        uri: mongodb://admin:secret@localhost:27017/product-service?authSource=admin
  rabbitmq:
      host: localhost
      port: 5672
      user: guest
      password: guest   
         
config:
  key: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
         include: "*"      
