
server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb: 
        uri: mongodb://admin:secret@localhost:27017/product-service?authSource=admin
  rabbitmq:
      host: localhost
      port: 5672
      user: guest
      password: guest   
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/auth/realms/microservices-project-realm"        
config:
  key: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
